version: "3.8"
services:
  mongodb:
    image: mongo:5.0.9
    volumes: 
      - ./scripts:/scripts
    command: "ls -la /scripts"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
